version: "3.9"  # optional since v1.27.0
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app /usr/src/workspace/app
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}