version: "3.9"  # optional since v1.27.0
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: ["python"]
    command: ["app.py"]
    # command: ["sleep", "10m"]

